AlgoParams:
  model_config:
    model_name: ConvAutoEncoder
    model_path: ''
    output_activation: sigmoid   # will be overwritten as relu if use edge filter
    latent_dim: 512
  epochs: 500
  evaluation_period: 10
  learning_rate: 0.001
  loss_function: mean_squared_error
DataParams:
  dataset_name: dataset_anomaly
  data_root: dataset/weldingspot/
  train_batch_size: 128
  val_batch_size: 32
  test_batch_size: 32
  shuffle: true
  task_type: reconstruction
  edge_preprocess: false
JobParams:
  gpu: true
  job_name: ''
  run_mode: train
  seed: 1
  capture_video: false
  output_path: ''
  gpu_id: '0'
